\documentclass{article}
\usepackage[margin=1.0in]{geometry} % To set margins
\usepackage{amsmath}  % This allows me to use the align functionality.
                      % If you find yourself trying to replicate
                      % something you found online, ensure you're
                      % loading the necessary packages!
\usepackage{amsfonts} % Math font
\usepackage{fancyvrb}
\usepackage{hyperref} % For including hyperlinks
\usepackage[shortlabels]{enumitem}% For enumerated lists with labels specified
                                  % We had to run tlmgr_install("enumitem") in R
\usepackage{float}    % For telling R where to put a table/figure
\usepackage{natbib}        %For the bibliography
\bibliographystyle{apalike}%For the bibliography

\begin{document}
<<echo=F, message=F, warning=F>>=
library(tidyverse)
@

\cite{Kasdin25} show that dopamine in the brains of young zebra finches acts as 
a learning signal, increasing when they sing closer to their adult song and 
decreasing when they sing further away, effectively guiding their vocal 
development through trial-and-error. This suggests that complex natural 
behaviors, like learning to sing, are shaped by dopamine-driven reinforcement 
learning, similar to how artificial intelligence learns. You can find the 
paper at this link:
\href{https://www.nature.com/articles/s41586-025-08729-1}{{https://www.nature.com/articles/s41586-025-08729-1}.}.

Note they measure dopamine using fibre photometry, changes in the fluorescence
indicate dopamine changes in realtime. Their specific measurement considers 
changes in flourescence in 100-ms windows between 200 and 300 ms from the start 
of singing, averaged across development.

\begin{enumerate}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% CONDUCT A POWER ANALYSIS
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\item Using the \texttt{pwr} package for \texttt{R} \citep{pwr},
conduct a power analysis. How many observations would the researchers 
need to detect a moderate-to-large effect ($d=0.65$) when using 
$\alpha=0.05$ and default power (0.80) for a two-sided one sample 
$t$ test.

\textbf{Solution:} Using \texttt{pwr.t.test()}, the researchers would need 21 observations to detect a moderate-to-large effect (as the output was $n = 20.58039$).

<<echo = F, size="scriptsize", eval=T, message=F, warning=F>>=

#######################################################
# Libraries
#######################################################
library(pwr)
library(ggplot2)
library(tidyverse)
library(patchwork)
library(xtable)
library(e1071)
library(effectsize)
@
<<echo = T, size="scriptsize", eval=F, message=F, warning=F>>=
pwr.t.test(d = 0.65, # moderate-large effect
           power = 0.80,
           sig.level = 0.05,
           alternative = "two.sided",
           type = "one.sample")
@
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% COLLECT DATA
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\item Click the link to go to the paper. Find the source data for 
Figure 2. Download the Excel file. Describe what you needed to
do to collect the data for Figure 2(g). Note that you only need the 
\texttt{closer\_vals} and \texttt{further\_vals}. Ensure to 
\texttt{mutate()} the data to get a difference 
(e.g., \texttt{closer\_vals - further\_vals}).

\textbf{Solution:} To collect the data, we downloaded all of their Figure 2 data, went to the g tabs, then saved just the closer\_vals and further\_vals as a separate .csv file to easily use in our code. This was done by simply copying and pasting the two columns together. Mutating the data we also got the difference by subtracting between the two.
<<echo = T, size="scriptsize", eval=T, message=F, warning=F>>=
finch.data = read.csv("./41586_2025_8729_MOESM4_ESM.csv") |>
  mutate(difference = Closer_vals - Farther_vals)
  @
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% SUMMARIZE DATA
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\item Summarize the data.
\begin{enumerate}
  \item Summarize the further data. Do the data suggest that
   dopamine in the brains of young zebra finches decreases when
   they sing further away?
   \item Summarize the closer data. Do the data suggest that
   dopamine in the brains of young zebra finches increases when
   they sing closer to their adult song?
  \item Summarize the paired differences. Do the data suggest
  that there is a difference between dopamine in the brains of
  young zebra finches when they sing further away compared to 
  closer to their adult song?
  \item \textbf{Optional Challenge:} Can you reproduce Figure 2(g)?
  Note that the you can use \texttt{geom\_errorbar()} to plot
  the range created by adding the mean $\pm$ one standard deviation.
\end{enumerate}

\textbf{Solution:}
This indicates that the dopamine in the brains of young zebra finches decreases when they sing further from their adult song. Conversely, it increases when they are closer to the adult song, with a suggested difference between the two seen below. 
%converted table from rcode
\begin{table}[ht]
\centering
\caption{Summary of Closer, Further, and the difference in Dopamine}
\begin{tabular}{|l|r|r|r|r|r|r|}
\hline
 & Min. & 1st Qu. & Median & Mean & 3rd Qu. & Max. \\
\hline
Closer vals & 0.001082 & 0.089018 & 0.145534 & 0.156223 & 0.195670 & 0.339488 \\
Further vals & -0.60279 & -0.30926 & -0.18675 & -0.20272 & -0.12271 & -0.02993 \\
Difference & 0.04335 & 0.22864 & 0.33208 & 0.35895 & 0.46771 & 0.93188 \\
\hline
\end{tabular}
\end{table}


<<echo = F, size="scriptsize", eval=T, message=F, warning=F>>=

plot.finch = ggplot(finch.data, aes(x = difference)) + #assigns the data as the data frame and aes = x axis
  geom_histogram(aes(y=after_stat(density)), binwidth = 0.1, fill = "lightblue", color = "black") + #makes histogram
  labs(title = "Difference between closer and further", #titles and axis labels
       x = "Dopamine Difference", 
       y = "Density")
plot.finch
@
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% CONDUCT THE TESTS
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\item Conduct the inferences they do in the paper. Make sure to report the results
a little more comprehensively -- that is your parenthetical should look something
like: ($t=23.99$, $p<0.0001$; $g=1.34$; 95\% CI: 4.43, 4.60).\\
\textbf{Note:} Your numbers may vary slightly as they performed some unclear
correction of their $p$-values. I'm waiting to hear back from them via email!
\textbf{Solution:}
\begin{enumerate}
  \item ``The close responses had a large difference from 0 ($p=8.13 \times 10^{-9}$).''
  \item ``The far responses had a large difference from 0 ($p=2.59 \times 10^{-8}$).''
  \item ``The difference between populations was large ($p=1.04 \times10^{-8}$).''
\end{enumerate}

<<echo = T, size="scriptsize", eval=T, message=F, warning=F, results='hide'>>=
#Closer_vals
closer_t = t.test(x=finch.data$Closer_vals, alternative = "greater", mu = 0)
closer.t.stat = (closer_t[1]$statistic)
interpret_hedges_g(hedges_g(x = finch.data$Closer_vals, alternative = "greater", mu = 0))


#Farther_vals
farther_t = t.test(x=finch.data$Farther_vals, alternative = "less", mu = 0)
farther.t.stat = (farther_t[1]$statistic)
interpret_hedges_g(hedges_g(x = finch.data$Farther_vals, alternative = "less", mu = 0))

#Difference
difference_t = t.test(x=finch.data$difference, alternative = "two.sided", mu = 0) #two-sided
diff.t.stat = difference_t[1]$statistic
interpret_hedges_g(hedges_g(x = finch.data$difference, mu = 0)) #two-sided
@
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% CONDUCT THE TESTS
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\item Reverse engineer the hypothesis test plot from Lecture 20 to create accurate
hypothesis testing plots for each part of the previous question.

<<eval = T, echo = F, message = F, warning = F, size = "scriptsize">>=
#######################################################
# Plotting null T for each value
#######################################################
n <- length(finch.data$Closer_vals)

# For plotting the null distribution
ggdat.t <- tibble(t=seq(-5,5,length.out=1000))|>
  mutate(pdf.null = dt(t, df=n-1))

#observed points
ggdat.closer <- tibble(t    =  closer.t.stat, 
                    y    = 0) # to plot on x-axis
ggdat.farther <- tibble(t    =  farther.t.stat, 
                       y    = 0) # to plot on x-axis
ggdat.difference <- tibble(t    =  diff.t.stat, 
                       y    = 0) # to plot on x-axis

###############
#Plotting Closer:
###############
# Resampling to approximate the sampling distribution 
# on the data
x = finch.data$Closer_vals
mu0 = 0
s <- sd(x)
R <- 1000
resamples <- tibble(t=numeric(R))
for(i in 1:R){
  curr.sample <- sample(x=x,
                        size=n,
                        replace=T)
  resamples$t[i] = (mean(curr.sample)-mu0)/(sd(curr.sample)/sqrt(n))
}

t.breaks <- c(-5, qt(0.025, df = n-1), # rejection region (left)
              0, 
              qt(0.975, df = n-1), 5,  # rejection region (right)
              closer.t.stat)                  # t-statistic observed
xbar.breaks <- t.breaks * s/(sqrt(n)) + mu0


closer_plot <- ggplot() +
  # null distribution
  geom_line(data=ggdat.t, 
            aes(x=t, y=pdf.null))+
  geom_hline(yintercept=0) +
  # rejection regions
  geom_ribbon(data=subset(ggdat.t, t<=qt(0.025, df=n-1)), 
              aes(x=t, ymin=0, ymax=pdf.null),
              fill="grey", alpha=0.5)+
  geom_ribbon(data=subset(ggdat.t, t>=qt(0.975, df=n-1)), 
              aes(x=t, ymin=0, ymax=pdf.null),
              fill="grey", alpha=0.5)+
  # Resampling Distribution
  stat_density(data=resamples, 
               aes(x=t),
               geom="line", color="grey")+
  # plot observation point
  geom_point(data=ggdat.closer, aes(x=t, y=y),
             color="red") +
  # clean up aesthetics
  theme_bw()+
  scale_x_continuous("t",
                     breaks = round(t.breaks,2),
                     labels = round(t.breaks, 2),
                     sec.axis = sec_axis(~.,
                                         name = bquote(bar(x)),
                                         breaks = t.breaks,
                                         labels = round(xbar.breaks,2)))+
  ylab("Density")+
  ggtitle("T-Test for Mean Dopamine Closer to Adult Song")


###############
#Plotting Further:
###############
# Resampling to approximate the sampling distribution 
# on the data
x = finch.data$Farther_vals
mu0 = 0
s <- sd(x)
R <- 1000
resamples <- tibble(t=numeric(R))
for(i in 1:R){
  curr.sample <- sample(x=x,
                        size=n,
                        replace=T)
  resamples$t[i] = (mean(curr.sample)-mu0)/(sd(curr.sample)/sqrt(n))
}

t.breaks <- c(-5, qt(0.025, df = n-1), # rejection region (left)
              0, 
              qt(0.975, df = n-1), 5,  # rejection region (right)
              farther.t.stat)                  # t-statistic observed
xbar.breaks <- t.breaks * s/(sqrt(n)) + mu0


farther_plot <- ggplot() +
  # null distribution
  geom_line(data=ggdat.t, 
            aes(x=t, y=pdf.null))+
  geom_hline(yintercept=0) +
  # rejection regions
  geom_ribbon(data=subset(ggdat.t, t<=qt(0.025, df=n-1)), 
              aes(x=t, ymin=0, ymax=pdf.null),
              fill="grey", alpha=0.5)+
  geom_ribbon(data=subset(ggdat.t, t>=qt(0.975, df=n-1)), 
              aes(x=t, ymin=0, ymax=pdf.null),
              fill="grey", alpha=0.5)+
  # Resampling Distribution
  stat_density(data=resamples, 
               aes(x=t),
               geom="line", color="grey")+
  # plot observation point
  geom_point(data=ggdat.farther, aes(x=t, y=y), 
                                    color="red") +
  # clean up aesthetics
  theme_bw()+
  scale_x_continuous("t",
                     breaks = round(t.breaks,2),
                     labels = round(t.breaks, 2),
                     sec.axis = sec_axis(~.,
                                         name = bquote(bar(x)),
                                         breaks = t.breaks,
                                         labels = round(xbar.breaks,2)))+
  ylab("Density")+
  ggtitle("T-Test for Mean Dopamine Further from Adult Song")

###############
#Plotting Further:
###############
# Resampling to approximate the sampling distribution 
# on the data
x = finch.data$difference
mu0 = 0
s <- sd(x)
R <- 1000
resamples <- tibble(t=numeric(R))
for(i in 1:R){
  curr.sample <- sample(x=x,
                        size=n,
                        replace=T)
  resamples$t[i] = (mean(curr.sample)-mu0)/(sd(curr.sample)/sqrt(n))
}

t.breaks <- c(-5, qt(0.025, df = n-1), # rejection region (left)
              0, 
              qt(0.975, df = n-1), 5,  # rejection region (right)
              diff.t.stat)                  # t-statistic observed
xbar.breaks <- t.breaks * s/(sqrt(n)) + mu0


difference_plot <- ggplot() +
  # null distribution
  geom_line(data=ggdat.t, 
            aes(x=t, y=pdf.null))+
  geom_hline(yintercept=0) +
  # rejection regions
  geom_ribbon(data=subset(ggdat.t, t<=qt(0.025, df=n-1)), 
              aes(x=t, ymin=0, ymax=pdf.null),
              fill="grey", alpha=0.5)+
  geom_ribbon(data=subset(ggdat.t, t>=qt(0.975, df=n-1)), 
              aes(x=t, ymin=0, ymax=pdf.null),
              fill="grey", alpha=0.5)+
  # Resampling Distribution
  stat_density(data=resamples, 
               aes(x=t),
               geom="line", color="grey")+
  # plot observation point
  geom_point(data=ggdat.difference, aes(x=t, y=y), 
                                     color="red") +
  # clean up aesthetics
  theme_bw()+
  scale_x_continuous("t",
                     breaks = round(t.breaks,2),
                     labels = round(t.breaks, 2),
                     sec.axis = sec_axis(~.,
                                         name = bquote(bar(x)),
                                         breaks = t.breaks,
                                         labels = round(xbar.breaks,2)))+
  ylab("Density")+
  ggtitle("T-Test for Mean Difference in Dopamine")

(closer_plot / farther_plot)+ difference_plot
@

\end{enumerate}


\bibliography{bibliography}
\end{document}
